posts:          /actualites/:year/:month/:day/:slug/
categories:     /actualites/:slug/
persons:        /equipe/:slug/
diplomas:    /diplomes/:slug/
administrators: /equipe/:slug/roles/
teachers:       /equipe/:slug/programs/
researchers:    /equipe/:slug/articles/
