posts:          /actualites/:year/:month/:day/:slug/
categories:     /actualites/:slug/
persons:        /equipe/:slug/
organizations:  /organisations/:slug/
authors:        /equipe/:slug/actualites/
diplomas:       /diplomes/:slug/
